# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BazaarTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BazaarTestApp

  target 'BazaarTestAppTests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 4.4'
    pod 'SQLite.swift/SQLCipher', '~> 0.11.2'
    pod 'SwiftyJSON'

    # Pods for testing
  end

end
